### ISSUE TITLE
Bug when joining a new server

### ISSUE THREAD

**Issue by TheDiamondYT1** [shoghicp/FastTransfer#9]
On the server play.explosivepe.net, everything is fine in the lobby. Go through the faction portal. In factions we can see lobby chat and pop ups real time. However join the IP with port 19133 to directly join factions. It does not show.

**Comment by PEMapModder** [comment]
It does not show what?

**Comment by TheDiamondYT1** [comment]
@PEMapModder I have done some debugging and found out that when transferring servers, it does not disconnect you from the previous server, and still displays chat and popups from that server. 

You can also receive /tell messages but you cannot reply. If you type in chat in the second server (After transferring) the people in first server (Probably lobby, before transfer) cannot see your chat. 

This could probably be fixed by (After transfer) kicking the player from the game.

**Comment by PEMapModder** [comment]
No it cannot. The client will show a disconnect screen, not sure if it disconnects from second server.
This is entirely a client issue and FastTransfer cannot fix it properly, since any act of closing sockets will make the client show a disconnect screen. This cannot be correctly fixed without client update.
You can do SourceInterface::closeSession to temporarily hide the problem from your eyes, but you will end up using exceptionally much bandwidth (basically every client you transfer away will be DDoS'ing you together), as well as being unable to join back the old server without the client closing first as the client will continue sending data that RakLib considers as attacks and stop handling packets from that IP.
